install:
	cp ../../../out/artifacts/freechains_kt_main_jar/freechains.kt.main.jar /usr/local/bin/Freechains.jar
	cp slf4j-nop-2.0.0-alpha1.jar /usr/local/bin
	cp freechains-cli.sh          /usr/local/bin/freechains
	cp freechains-host.sh         /usr/local/bin/freechains-host
	#cp freechains-sync.sh         /usr/local/bin/freechains-sync
	ls -l /usr/local/bin/[Ff]reechains*
	freechains --version
